/*
 * File: app/view/Qa.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Stalfond.view.Qa', {
    extend: 'Ext.container.Container',
    alias: 'widget.kladr',

    requires: [
        'Stalfond.view.QaViewModel',
        'Ext.form.field.Trigger',
        'Ext.form.FieldContainer',
        'Ext.form.field.ComboBox'
    ],

    viewModel: {
        type: 'kladr'
    },
    layout: 'column',

    items: [
        {
            xtype: 'triggerfield',
            columnWidth: 1,
            labelWidth: 140,
            name: 'FullAddress',
            editable: false,
            emptyText: 'Введите адрес'
        },
        {
            xtype: 'fieldcontainer',
            columnWidth: 1,
            itemId: 'menu',
            padding: 0,
            width: 1052,
            defaults: {
                columnWidth: 0.5,
                margin: '5 0 5 10',
                labelWidth: 120,
                queryMode: 'remote'
            },
            layout: 'column',
            hideEmptyLabel: false,
            labelPad: 0,
            labelWidth: 0,
            items: [
                {
                    xtype: 'combobox',
                    fieldLabel: 'Субъект РФ',
                    name: 'Subject',
                    blankText: 'Поле "Субъект РФ" обязательно для заполнения',
                    matchFieldWidth: false,
                    displayField: 'Name',
                    forceSelection: true,
                    minChars: 1,
                    pageSize: 25,
                    valueField: 'ID'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'Район',
                    name: 'RegionArea',
                    matchFieldWidth: false,
                    displayField: 'Name',
                    forceSelection: true,
                    minChars: 1,
                    pageSize: 25,
                    valueField: 'ID'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'Город',
                    name: 'City',
                    matchFieldWidth: false,
                    displayField: 'Name',
                    forceSelection: true,
                    minChars: 1,
                    pageSize: 25,
                    valueField: 'ID'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'Населенный пункт',
                    preventMark: true,
                    name: 'Town',
                    matchFieldWidth: false,
                    displayField: 'Name',
                    forceSelection: true,
                    minChars: 1,
                    pageSize: 25,
                    valueField: 'ID'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'Улица',
                    name: 'Street',
                    matchFieldWidth: false,
                    displayField: 'Name',
                    forceSelection: true,
                    minChars: 1,
                    pageSize: 25,
                    valueField: 'ID'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Индекс',
                    name: 'Index'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Код терр. деления',
                    name: 'GNINMB'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Дом',
                    name: 'House'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Корпус/строение',
                    name: 'Building'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Квартира/офис',
                    name: 'Room'
                }
            ]
        }
    ]

});